### ISSUE TITLE
[Question] Is it possible to read calypso card on iOS?

### ISSUE THREAD

**Issue by lorenc-tomasz** [eclipse-keyple/keyple-plugin-android-nfc-java-lib#8]
Hi,
I'm wondering if it's possible to read Calypso card on iOS?

**Comment by jeanpierrefortune** [comment]
Hi,

Thank you for your question about reading Calypso cards on iOS with the Keyple NFC plugin.

I apologize for the late response to your question. It looks like this issue was opened several weeks ago, and we regret that we were not able to respond to your question sooner.

To answer your question, while Keyple does not provide native support for iOS, it is indeed possible to read Calypso cards on iOS using Keyple, albeit with some additional development work.

Since Keyple is a Java-based framework, and iOS does not support Java development natively, it is necessary to develop an iOS client application using a supported language such as Swift or Objective-C. This client application can then connect to a Keyple server using the "[Server JSON API for non-Keyple clients](https://keyple.org/learn/user-guide/server-json-api/)". This API allows non-Keyple clients to communicate with a Keyple server using JSON messages over HTTP or WebSocket.

By using this approach, the transaction is piloted by Keyple on the server side, and the iOS client application acts as a remote interface to the server. This means that the Keyple server handles the communication with the Calypso card, and the iOS client application simply sends and receives JSON messages to and from the server.

I hope this information is helpful, even though it is coming several weeks after your initial question. If you have any further questions, please don't hesitate to ask.

Best regards,
Jean-Pierre Fortune
